### ISSUE TITLE
Mot masculin

### ISSUE THREAD

**Issue by chevrelo** [CPLN/enigmos#11]
Seul mot masculin NON-COMPOSÉ qui se termine par "ette".

Mot : Squelette

Indice : Tous le monde en a un constitué d'os.

**Comment by SteeveDroz** [comment]
Faut-il aussi accepter "lette", "trompette" et "exosquelette" ?

**Comment by chevrelo** [comment]
Exosquelette est un mot composé non ?

Et les autres sont tous des mots féminins (j'ai vérifié ^^).

**Comment by SteeveDroz** [comment]
[Un lette](https://fr.wiktionary.org/wiki/lette#Nom_commun_1)
[Un trompette](http://www.francaisfacile.com/exercices/exercice-francais-2/exercice-francais-88884.php)
