### ISSUE TITLE
Énigme Under the Keyboard

### ISSUE THREAD

**Issue by VincentRime** [CPLN/enigmos#124]
il y a une image de clavier avec un mot à écrire sur le clavier. Quand on clique sur une touche du clavier avec la souris il y aura une animation de "clique" mais pour trouver la réponse il faudra tirer les lettres avec la souris pour pouvoir voir les lettres en dessous qui nous indiquerons de les reliez. Ensuite il faudra relier les trois lettres manquante entre elles ce qui créera une triangle et l'image illuminati s'affichera et la réponse sera illuminati.

**Comment by SteeveDroz** [comment]
Bon travail !
