### ISSUE TITLE
Jeu du sac

### ISSUE THREAD

**Issue by DiavoloKingCrimson** [CPLN/enigmos#127]
L'on se déplace dans une petite école et on doit trouver 6 papier cachés dans les salles de classe pour former un mot.
il devra donc se déplacer de salle en salle en passant par les couloirs, sauf qu'ils sont infesté de fantôme
qu'il ne faut pas regarder dans les yeux ou c'est un game over.
les fantôme se déplace selon un patern prédéfini qui effectue des allers-retours.

cependant le joueur aura aussi besoin du sac qui est dans la première salle qui contient l'autre moitié du mot de passe

en résumé pour gagner le joueur devra avoir trouvé les six papier et le sac

**Comment by SteeveDroz** [comment]
Bon travail !
