### ISSUE TITLE
Les singes animés

### ISSUE THREAD

**Issue by AnaKamelia** [CPLN/enigmos#129]
Il y a trois singes sur l'écran avec des boutons en dessous. Chaque bouton permet des action différentes, parmi elles : animer/arrêter un singe ou encore inverser son état (si il bougeait, il ne bouge plus et si il ne bougeait pas, il se met à bouger).

Le but est de trouver quels boutons cliquer et dans quel ordre, pour que les trois singes s'animent en même temps.

Si l'utilisateur réussi un pop-up apparaît avec le mot de passe pour passer à l'énigme suivante.

**Comment by SteeveDroz** [comment]
Je ne suis pas trop fan des popups et j'essaye de les éliminer des énigmes précédentes, mais sinon, c'est bon!

**Comment by SteeveDroz** [comment]
Bon travail !
