### ISSUE TITLE
Forme en folie

### ISSUE THREAD

**Issue by Sandozor** [CPLN/enigmos#130]
Il s'agit d'un petit jeu dans lequel on commence avec une forme d'une certaine couleur, par exemple un carré vert. Ensuite, il va s'afficher une deuxième forme soit totalement différente (un rond rouge) ou une forme identique mais d'une autre couleur ou encore juste la forme qui change, mais la forme peut tout autant rester identique.
L'utilisateur aura deux choix à chaque fois (différent ou identique), il devra donc déterminer si la couleur ou la forme (cela sera aléatoire) est identique ou non à la forme précédente.
Il y aura un temps imparti que je choisirai plus tard en fonction de la difficulté pour répondre à environ 15 étapes sans erreur. 
A la fin s'affichera : "La réponse est la couleur de la première forme".

**Comment by SteeveDroz** [comment]
Terminé.
