### ISSUE TITLE
Donjon de la foulque des ténèbres

### ISSUE THREAD

**Issue by RenatoAL** [CPLN/enigmos#131]
Ceci est une énigme où une brave foulque doit trouver 3 lettres cachés dans le donjon. Chaque salle a des éléments spéciaux. Les ennemis doivent être battus avec des petites énigmes. Le portail ne peut être pris qu'ne fois que la foulque parle avec le Nécromancien et devient LA FOULQUE DES TÉNÈBRES!!! 

Une fois qu'on a les trois lettres on les mets en ordre et on trouve le mot secret.

![sans titre](https://cloud.githubusercontent.com/assets/27847325/25272264/802b5e1e-2687-11e7-8b42-feb20397024a.png)

**Comment by SteeveDroz** [comment]
OK, mais enlevez les énigmes dans chaque salle, il suffit de s'y rendre et de faire toujours la même chose, sinon vous refaites un Enigmos dans Enigmos.

**Comment by RenatoAL** [comment]
On oppresse ma créativité mais je vais dans les moyens disponibles faire en sorte que ça marche.

**Comment by AnaKamelia** [comment]
EnigmosCeption (°O°)

**Comment by SteeveDroz** [comment]
Bon travail !
