### ISSUE TITLE
Jeu du rébus

### ISSUE THREAD

**Issue by danydacosta** [CPLN/enigmos#132]
L'interface se compose de 3 images (peut être plus ?) et d'un champs de texte, le but, comme le veut ce célèbre jeu, est de retrouver une phrase en fonction de ces 3 images. 

Exemple :

[Image](http://devinettedujour.com/wp-content/uploads/2016/06/rebus-enfant-223.jpg)

Et la réponse: Escarmouche

Jeu simple mais efficace qui demande de la réflexion. Peu original mais pourquoi réinventer la roue ? :)

**Comment by SteeveDroz** [comment]
Bon travail !
