### ISSUE TITLE
Ré-organisation des fichiers images

### ISSUE THREAD

**Issue by danydacosta** [CPLN/enigmos#140]
Il semble que le projet contienne deux dossiers contenant des images. Pourquoi ne pas les ré-organiser dans un seul dossier img et créer des sous-dossiers pour chaque enigme. Comme cela, chaque énigme aura son propre dossier image. La simplification de l'arborescence améliore l'ergonomie et ce sera plus simple pour un programmeur de s'y retrouver.

**Comment by SteeveDroz** [comment]
Bon travail !
