### ISSUE TITLE
Devine l'animal !

### ISSUE THREAD

**Issue by DarmangerDavid** [CPLN/enigmos#145]
Une image qui formera la silhouette d'un animal sera en noir et le but sera de deviner l'animal. On pourra deviner l'animal grâce à trois bouton. Il aura 2 chances pour trouver l'animal.

Dans ce cas-là, ce sera un éléphant mais malheureusement il ressemblera à une raie manta ou à un papillon. Les trois boutons seront "éléphant", "raie manta", "papillon".

Une fois l'animal trouvé la réponse s'affichera. La réponse est "éléphant".

**Comment by SteeveDroz** [comment]
Bon travail.
