### ISSUE TITLE
Pile ou face !

### ISSUE THREAD

**Issue by Mozerskial** [CPLN/enigmos#146]
Pile ou face !
Au départ le joueur 1 (nous) choisi une combinaison de 3 "pile" ou "face" ex: "pile,pile,face" , le joueur 2 choisi l'inverse ex: "face,face,pile". 
Pour réussir , le joueur 1 doit avoir au moins 75%(2/3 des réponses) correctes dans sa combinaison.
Si sa combinaison contient 3 réponses correctes , il obtient alors un trophée avec la réponse complète.
Si sa combinaison contient 2 réponses correctes , il obtient le choix entre 2 trophée avec chacun une partie de la réponse et un bouton recommencer.
Si sa combinaison contient moins de 2 réponse correctes , la partie recommence.

**Comment by SteeveDroz** [comment]
Pourquoi un joueur 2 ? Pourquoi pas simplement réussi/raté ?

Depuis quand 75% = 2/3 ?

**Comment by Mozerskial** [comment]
le joueur 2 serait le programme mais je suis pas obligé de le mettre , une fois réfléchi

**Comment by SteeveDroz** [comment]
Bon travail !
