### ISSUE TITLE
Le jeu du clou

### ISSUE THREAD

**Issue by danydacosta** [CPLN/enigmos#150]
Un clou est planté à 1/12 de sa longueur dans une table, le jeu se joue au tour par tour contre une IA. Le but ? Être celui qui donnera le coup fatal en enfonçant le clou totalement dans la table. Le jeu se joue en BO3 (3 manches, le joueur l'emporte quand il en gagne au moins 2). La puissance des coups se gère grâce à une barre d'énergie. Je sais que ce n'est pas vraiment un énigme mais je trouve ce jeu vraiment cool et je pense qu'il a sa place dans le projet !

**Comment by danydacosta** [comment]
@SteeveDroz C'est dérangeant si je place mes classes dans un dossier propre à mon énigme situé dans Components au lieu de les places en vrac dans le dossier ?

Exemple:

Enigmas----|
                    Components----|
                                                EnigmeClou----|
                                                                           class1.cs
                                                                           class2.cs

Je demande car je sais sais pas si ça peut poser un soucis et je préfère être sûr !

**Comment by SteeveDroz** [comment]
Il n'y a aucun problème technique avec ça, mais respectez les conventions en vigueur et mettez tout dans le même.

Et au fait, tout ce qui commence par 4 caractères *espace*, en MarkDown, est considéré comme du code. Exemple :

    Enigmas----|
               Components----|
                             EnigmeClou----|
                                           class1.cs
                                           class2.cs

**Comment by SteeveDroz** [comment]
Bon travail !
