### ISSUE TITLE
Trouver la réponse

### ISSUE THREAD

**Issue by SteveCorreia** [CPLN/enigmos#151]
Le but de ce jeu est simplement de trouver la réponse. 
Comme par exemple : 
2 + 2 = Poisson
3 + 3 = Huit
7 + 7 = ?

**Comment by SteeveDroz** [comment]
Triangle !

**Comment by SteveCorreia** [comment]
J'ai changé d'énigme voici la nouvelle :
Compléter cette suite : 
69 - SF - 10 - DX- 97 - NT - 31 - ?

**Comment by SteeveDroz** [comment]
Elle n'a plus rien à voir, merci d'en proposer une autre.
