### ISSUE TITLE
Compteur

### ISSUE THREAD

**Issue by AurelieWasem** [CPLN/enigmos#153]
Une durée est proposée : 5, 10 ou 15 secondes.
L'utilisateur à une marge de 0.15 secondes. 
Le chronomètre s'enclenche . 
L'utilisateur doit alors compter mentalement et appuyer sur la barre espace quand il estime avoir atteint la durée demandée. Le compteur est alors dévoilé s'il est dans la limite la réponse s'affiche sinon c'est un bouton recommencer.
Réponse: "temps"

**Comment by SteeveDroz** [comment]
Je ne laisserais pas la durée à choix, pourquoi ne pas avoir une durée aléatoire choisie à chaque fois ? (entre 5 et 15 secondes).

**Comment by SteeveDroz** [comment]
Bon travail !
