### ISSUE TITLE
NFSEnigmaPanel ne se réinitialise pas

### ISSUE THREAD

**Issue by misterkonik** [CPLN/enigmos#159]
Si on finit NFSEnigmaPanel mais que l'on ne rentre pas la réponse dans la textbox de réponse et que l'on appuis sur la bouton passée et si on reviens dessus plus tard l'énigme ne se reset pas et il n'est plus possible d'avoir sa réponse.

**Comment by SteeveDroz** [comment]
Merci @PicchiEv !
