### ISSUE TITLE
Rebus simple

### ISSUE THREAD

**Issue by damienschindler** [CPLN/enigmos#162]
L'utilisateur doit trouver la réponse grâce à trois images.

![4_des_rouge](https://cloud.githubusercontent.com/assets/27950259/26299548/79c9c3dc-3edb-11e7-92da-ba0eb171c7ce.png)
![cape](https://cloud.githubusercontent.com/assets/27950259/26299553/7d3827e8-3edb-11e7-8f26-90510c9861be.png)
![eau_robinet](https://cloud.githubusercontent.com/assets/27950259/26299558/8125e872-3edb-11e7-8b28-9618be4c4083.jpg)
![table](https://cloud.githubusercontent.com/assets/27950259/26299564/859676e2-3edb-11e7-9725-a2a461d5498c.jpg)

Indice : Résolvez le rébus
Réponse : Décapotable (Dés-cape-eau-table)

**Comment by SteeveDroz** [comment]
Il y a déjà un rébus dans Enigmos
