### ISSUE TITLE
Les boutons d'EnigmaPanel ne perdent pas leur focus quand on clique dessus.

### ISSUE THREAD

**Issue by danydacosta** [CPLN/enigmos#165]
## Reproduire le problème:

Quand l'utilisateur se trouve sur une énigme qui requiert des saisies claviers (grâce à la méthode `PressKey()`) et qu'il presse sur le bouton pour afficher les astuces, lors de la fermeture de la boîte de dialogue le bouton ne perd pas le focus (l'encadré bleu reste). Le problème, c'est que quand un contrôle comme un bouton est focus, n'importe quelle touche pressée par l'utilisateur va appeler l'évènement dudit bouton, ce qui empêche la capture de touche sur une énigme. Pour remédier à ce problème, l'utilisateur doit cliquer quelque part d'autre que le bouton pour perdre le focus et ensuite l'énigme peut à nouveau capturer les saisies claviers.

Déjà que certaines énigmes nécessitent de se creuser la tête, il ne faudrait pas frustrer le joueur avec une ergonomie douteuse...

## Régler le problème:

Il faudrait qu'après que le bouton pour les astuces soit cliqué, perdre immédiatement le focus sur ce contrôle.

**Comment by SteeveDroz** [comment]
Résolu par #166, merci !
