### ISSUE TITLE
ClouEnigmaPanel  commande non bloqué

### ISSUE THREAD

**Issue by misterkonik** [CPLN/enigmos#176]
Il y a la possibilité d'appuyer plusieurs fois sur la touche espace pendant son tour de jeu et ensuite on ne peut plus rien faire pendant nos tours de jeu suivant tant que le nombre de fois où on a appuyé sur la touche espace au premier tour n'est pas dépassé.

**Comment by SteeveDroz** [comment]
@danydacosta, votre avis ?

**Comment by danydacosta** [comment]
C'est effectivement un bug, je me charge de le résoudre au plus vite !

**Comment by danydacosta** [comment]
@SteeveDroz, ce bug a été corrigé dans mon dernier pull request:  #178.

**Comment by SteeveDroz** [comment]
Merci
