### ISSUE TITLE
Hidden character

### ISSUE THREAD

**Issue by BryanFerreira** [CPLN/enigmos#20]
Lorsque le curseur passe dans le panel, il le colorie en une couleur différente de celle de l'arrière plan.
Pendant le coloriage un caractère ASCII sera trouvé. L'utilisateur l'insère dans le TextBox et passe à la prochaine énigme.
![enigmos1](https://cloud.githubusercontent.com/assets/15800074/11092222/ccfdb7c8-8881-11e5-9293-066e54e97808.png)

**Comment by SteeveDroz** [comment]
Ok, mais avec un mot, pas juste une lettre.
