### ISSUE TITLE
La course de cheval

### ISSUE THREAD

**Issue by VincentGremion** [CPLN/enigmos#29]
Un vieil homme dit à ses deux fils : "Celui dont le cheval arrivera en dernier à la ville, obtiendra mon héritage." 
Pourtant les deux hommes firent la course pour aller à destination. Pourquoi ? 

Réponse : Ils avaient chacun pris le cheval de l'autre

**Comment by SteeveDroz** [comment]
Non :
- C'est une question textuelle, sans interaction.
- Comment faire pour vérifier la réponse ? Il faut un mot, pas une phrase.
