### ISSUE TITLE
Quel jour de la semaine ?

### ISSUE THREAD

**Issue by chevrelo** [CPLN/enigmos#37]
Si nous ne sommes pas le lendemain de lundi ou le jour avant jeudi, que demain n'est pas dimanche, que ce n'était pas dimanche hier et que le jour d'après-demain n'est pas samedi, et que le jour avant hier n'était pas mercredi.

Quel jour sommes-nous ?

Réponse : Dimanche.

Indice : Entre lundi et dimanche.

**Comment by SteeveDroz** [comment]
C'est une question avec que du texte... **ENCORE** !
