### ISSUE TITLE
Tape-taupe

### ISSUE THREAD

**Issue by Chiffellej** [CPLN/enigmos#48]
le but du jeu est de cliquer sur les taupes qui vont apparaître, il faudra en taper 10 dans un temps limité

**Comment by AnaKamelia** [comment]
A corriger : Ne se relance pas lorsque l'on perds à cause du dépassement du temps à disposition, ou si l'on clique sur un chat. Il faut obligatoirement passer l'énigme.

**Comment by SteeveDroz** [comment]
Bug teansféré vers #120.
