### ISSUE TITLE
Roux run

### ISSUE THREAD

**Issue by Boschar** [CPLN/enigmos#61]
Il y a trois voie et un personnage qui court. Il doit éviter les obstacles jusqu'à arriver en sécurité pour pouvoir gagner. Pour éviter les obstacles il doit changer de voie.

**Comment by SteeveDroz** [comment]
@CPLN/enigmos avec cette énigme, le nombre de niveaux dans Enigmos monte à 20 et le logiciel passe en version bêta.

## Bravo à tous !
