### ISSUE TITLE
Problème d'encodage

### ISSUE THREAD

**Issue by greut** [CPLN/enigmos#69]
![capture d ecran de 2015-11-18 19-44-24](https://cloud.githubusercontent.com/assets/1388/11250457/cf5d53c4-8e2c-11e5-8643-73a003b1cbf9.png)

Testé avec Mono.

**Comment by SteeveDroz** [comment]
@greut, comment tu as fait pour avoir cette erreur ? Elle ne se produit pas chez moi et j'ai vérifié, les fichiers sont en UTF-8. [Le fichier source](https://github.com/CPLN/enigmos/blob/master/Enigmas/CharadeEnigmaPanel.cs) est d'ailleurs sans erreur d'encodage sur Github...

**Comment by greut** [comment]
Corrigé magiquement.

![capture d ecran de 2015-11-19 08-56-30](https://cloud.githubusercontent.com/assets/1388/11265286/78d5b770-8e9b-11e5-9deb-d1fc5a2984e0.png)
